import Foundation
import IsolationCore

/// Parses a `key.symbol_graph` document's declaration fragments -- the primary, structured format
/// per the binding design (`"kind": "attribute"` JSON fragments, global-actor name via
/// `preciseIdentifier`, never text/substring scanning).
///
/// Return-value contract, important and easy to get backwards: `nil` means the JSON itself could
/// not be parsed (a real format failure -- the caller must treat this as `unknown`, per the
/// binding design). A **matched, successfully-parsed** result with **no attribute fragment at
/// all** is not a failure -- for a symbol-graph document generated by a live, per-declaration
/// `cursorinfo` query, it is the compiler's genuine, positive signal that this declaration has no
/// isolation of its own (`ActorIsolation::Unspecified` never gets an attribute attached at all,
/// confirmed directly in `swiftlang/swift`'s `TypeCheckConcurrency.cpp`,
/// `addAttributesForActorIsolation`, and empirically via the research spike's own negative
/// control) -- that case returns `.nonisolated`, a real fact, not `nil`.
///
/// **That premise does not hold for a whole-module `swift symbolgraph-extract` dump** (confirmed
/// directly, not assumed: `UINavigationController.pushViewController(_:animated:)`'s own
/// `declarationFragments` in a real `symbolgraph-extract -module-name UIKit` output carry no
/// attribute at all, while a live `cursorinfo` query at a real call site of the *same* USR returns
/// `declarationFragments` that do include `@MainActor` -- `addAttributesForActorIsolation`'s
/// per-declaration resolution runs for a live query but is not restated in a member's own bulk
/// symbol-graph entry when the isolation comes from the *containing type*, e.g. `@MainActor class
/// UINavigationController` inherited by every instance method it declares, never repeated on each
/// one). `hasConfirmedIsolationSignal(_:)` exists for exactly this: a caller reading bulk-extracted
/// fragments (`BulkSymbolGraphExtractor`) must not treat "no attribute" as confirmed `.nonisolated`
/// the way a live-query caller safely can.
public enum SymbolGraphIsolationParser {
    public static func isolation(fromSymbolGraphJSON json: String, knownGlobalActorNames: Set<String>) -> IsolationKind? {
        guard let data = json.data(using: .utf8),
              let document = try? JSONDecoder().decode(SymbolGraphDocument.self, from: data),
              let symbol = document.symbols.first else {
            return nil
        }
        return isolation(fromFragments: symbol.declarationFragments ?? [], knownGlobalActorNames: knownGlobalActorNames)
    }

    static func isolation(fromFragments fragments: [SymbolGraphDocument.Symbol.Fragment], knownGlobalActorNames: Set<String>) -> IsolationKind {
        for fragment in fragments where fragment.kind == "attribute" {
            if fragment.spelling == "nonisolated" {
                return .nonisolated
            }
            // The bare "@" punctuation fragment has no `preciseIdentifier`; the actor-name
            // fragment that follows it does (e.g. `s:ScM` for `MainActor`) -- necessary, but not
            // sufficient, evidence this fragment names a real global actor: a resolvable USR only
            // means the fragment references *some* real type, not that the type is a global actor
            // (see `GlobalActorNameValidation`'s own doc comment -- `@StateObject` resolves just as
            // cleanly and is not an actor at all).
            if let usr = fragment.preciseIdentifier,
               GlobalActorNameValidation.isGlobalActorName(spelling: fragment.spelling, usr: usr, knownGlobalActorNames: knownGlobalActorNames) {
                return .globalActor(name: fragment.spelling)
            }
        }
        return .nonisolated
    }

    /// `true` when `fragments` carry an explicit, confirmed isolation signal -- a `nonisolated`
    /// keyword, or an attribute naming a real global actor. `isolation(fromFragments:)` returns
    /// `.nonisolated` both when this is `true` (a real fact) and when it's `false` (no signal at
    /// all, ambiguous for bulk-extracted data per this type's own doc comment) -- callers that
    /// cannot treat those two cases the same way (`BulkSymbolGraphExtractor`) need this to tell
    /// them apart; a live-query caller does not, since a live query's own absence of an attribute
    /// is already a confirmed fact.
    static func hasConfirmedIsolationSignal(_ fragments: [SymbolGraphDocument.Symbol.Fragment], knownGlobalActorNames: Set<String>) -> Bool {
        for fragment in fragments where fragment.kind == "attribute" {
            if fragment.spelling == "nonisolated" {
                return true
            }
            if let usr = fragment.preciseIdentifier,
               GlobalActorNameValidation.isGlobalActorName(spelling: fragment.spelling, usr: usr, knownGlobalActorNames: knownGlobalActorNames) {
                return true
            }
        }
        return false
    }
}

struct SymbolGraphDocument: Decodable {
    let symbols: [Symbol]

    struct Symbol: Decodable {
        let declarationFragments: [Fragment]?

        struct Fragment: Decodable {
            let kind: String
            let spelling: String
            let preciseIdentifier: String?
        }
    }
}
